

import os
from dotenv import load_dotenv
import logging
from anthropic import Anthropic


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def build_persona_with_llm(user_data: dict) -> str:
    """
    Scraped user data ka use karke Anthropic LLM se user persona generate karta hai.
    """
    load_dotenv() # Ensure .env is loaded for ANTHROPIC_API_KEY
    anthropic_api_key = os.getenv("ANTHROPIC_API_KEY")

    if not anthropic_api_key:
        logging.error("ANTHROPIC_API_KEY .env file mein set nahi hai.")
        raise ValueError("Anthropic API key missing. Please set ANTHROPIC_API_KEY in your .env file.")

    client = Anthropic(api_key=anthropic_api_key)
    
    username = user_data['username']
    
    
    comments_text = "\n".join([f"Comment ({c['id']}) in r/{c['subreddit']}: {c['body']} [Link: {c['permalink']}]" for c in user_data['comments']])
    posts_text = "\n".join([f"Post ({p['id']}) in r/{p['subreddit']}: Title: {p['title']} Body: {p['selftext']} [Link: {p['permalink']}]" for p in user_data['posts']])

    
    prompt_template = f"""
    You are an expert User Persona generator. Your task is to analyze the provided Reddit comments and posts of a user and create a detailed user persona.
    The persona should be structured similar to a standard user persona document, covering aspects like:
    - **Basic Info**: Age (infer if possible, otherwise state 'N/A'), Occupation (infer if possible, otherwise 'N/A'), Interests, Location (infer if possible, otherwise 'N/A').
    - **Personality Traits**: Describe their general personality based on their tone, engagement, and topics. Use a few adjectives.
    - **Motivations**: What drives them? What do they care about?
    - **Goals & Needs**: What are they trying to achieve or what problems are they trying to solve?
    - **Frustrations**: What causes them annoyance or difficulty, as expressed in their posts/comments?
    - **Behavior & Habits**: How do they typically interact on Reddit? What kind of content do they engage with? Any recurring themes or topics?
    - **Quote**: A representative quote that summarizes their primary mindset or motivation.

    For EACH piece of information or characteristic you identify in the persona (e.g., an interest, a motivation, a frustration), you MUST cite the specific Reddit comment or post ID and its permalink that led you to that conclusion. If possible, include a small snippet from the cited content.

    Here is the Reddit data for user /u/{username}:

    --- Reddit Comments ---
    {comments_text}

    --- Reddit Posts ---
    {posts_text}

    Please generate the user persona in a clear, well-structured text format.
    """
    
    logging.info(f"Generating persona for /u/{username} using Anthropic LLM...")
    try:
        message = client.messages.create(
            model="claude-3-5-sonnet-20240620", # Updated model name
            max_tokens=2000,
            messages=[
                {"role": "user", "content": prompt_template}
            ]
        )
        persona_content = message.content[0].text
        logging.info("Persona generated by LLM.")
        return persona_content
    except Exception as e:
        logging.error(f"LLM se persona generate karne mein error: {e}", exc_info=True)
        raise # Re-raise for FastAPI to catch and handle

if __name__ == "__main__":
    # Yeh part sirf testing ke liye hai, real app mein isko FastAPI/Streamlit handle karega
    # Example usage:
    # dummy_user_data = {
    #     "username": "testuser",
    #     "comments": [{"id": "c1", "subreddit": "test", "body": "This is a test comment.", "permalink": "link1", "score":1}],
    #     "posts": [{"id": "p1", "subreddit": "test", "title": "Test Post", "selftext": "Test body", "url": "", "permalink": "link2", "score":1}]
    # }
    # persona = build_persona_with_llm(dummy_user_data)
    # print(persona)
    pass